python AllenSDK_bgsubs_after_NAOMi.py Raw
python AllenSDK_bgsubs_after_NAOMi.py SNR
python AllenSDK_bgsubs_after_1p.py Raw
python AllenSDK_bgsubs_after_1p.py SNR
python AllenSDK_bgsubs_after_ABO.py Raw
python AllenSDK_bgsubs_after_ABO.py SNR
