python CNMF_unmixing_seeded_ABO.py Raw
python CNMF_unmixing_seeded_ABO.py SNR
python CNMF_unmixing_seeded_NAOMi.py Raw
python CNMF_unmixing_seeded_NAOMi.py SNR
python CNMF_unmixing_seeded_1p.py Raw
python CNMF_unmixing_seeded_1p.py SNR